In [3]:
#using Logistic Regression as a classifier

#clients similiar to A did or did not like product based on ...

import numpy as np
import pandas as pd
from pandas import Series, DataFrame
from sklearn.linear_model import LogisticRegression

In [4]:
bankFull = pd.read_csv("C:/Users/P/OneDrive/Desktop/Dev Projects/Recommendation System ML AI/bank_full_w_dummy_vars.csv")

In [5]:
bankFull.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,...,job_unknown,job_retired,job_services,job_self_employed,job_unemployed,job_maid,job_student,married,single,divorced
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,...,0,0,0,0,0,0,0,1,0,0
1,44,technician,single,secondary,no,29,yes,no,unknown,5,...,0,0,0,0,0,0,0,0,1,1
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,...,0,0,0,0,0,0,0,1,0,0
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,...,0,0,0,0,0,0,0,1,0,0
4,33,unknown,single,unknown,no,1,no,no,unknown,5,...,1,0,0,0,0,0,0,0,1,1

In [6]:
bankFull.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 37 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   age                           45211 non-null  int64
 1   job                           45211 non-null  object
 2   marital                       45211 non-null  object
 3   education                     45211 non-null  object
 4   default                       45211 non-null  object
 5   balance                       45211 non-null  int64
 6   housing                       45211 non-null  object
 7   loan                          45211 non-null  object
 8   contact                       45211 non-null  object
 9   day                           45211 non-null  int64
 10  month                         45211 non-null  object
 11  duration                      45211 non-null  int64
 12  campaign                      45211 non-null  int64
 13  pdays                         45211 non-null  int64
 14  previous                      45211 non-null  int64
 15  poutcome                      45211 non-null  object
 16  y                             45211 non-null  object
 17  y_binary                      45211 non-null  int64
 18  housing_loan                  45211 non-null  int64
 19  credit_in_default             45211 non-null  int64
 20  personal_loans                45211 non-null  int64
 21  prev_failed_to_subscribe      45211 non-null  int64
 22  prev_subscribed               45211 non-null  int64
 23  job_management                45211 non-null  int64
 24  job_tech                      45211 non-null  int64
 25  job_entrepreneur              45211 non-null  int64
 26  job_bluecollar                45211 non-null  int64
 27  job_unknown                   45211 non-null  int64
 28  job_retired                   45211 non-null  int64
 29  job_services                  45211 non-null  int64
 30  job_self_employed             45211 non-null  int64
 31  job_unemployed                45211 non-null  int64
 32  job_maid                      45211 non-null  int64
 33  job_student                   45211 non-null  int64
 34  married                       45211 non-null  int64
 35  single                        45211 non-null  int64
 36  divorced                      45211 non-null  int64
dtypes: int64(27), object(10)
memory usage: 12.8+ MB

In [65]:
#y_binary is binary version of target variable
#use y_binary to train model and predict if new users will subscribe based on user attributes

x = bankFull.iloc[:, 18:36].values

y = bankFull.iloc[:, 17:].values
y=y.flatten()
y

array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

In [66]:
LogReg = LogisticRegression()
LogReg.fit(x, y)

ValueError: Found input variables with inconsistent numbers of samples: [45211, 904220]